import {
  Injectable,
  UnauthorizedException,
  ConflictException,
  BadRequestException,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import * as bcrypt from 'bcryptjs';
import { Tourist } from '../../entities/tourist.entity';
import { LoginDto, RegisterDto } from './dto/auth.dto';
import { RedisService } from '../../config/redis.service';

@Injectable()
export class AuthService {
  constructor(
    @InjectRepository(Tourist)
    private touristRepository: Repository<Tourist>,
    private jwtService: JwtService,
    private redisService: RedisService,
  ) {}

  async register(registerDto: RegisterDto) {
    const { email, phoneNumber, password, ...userData } = registerDto;

    // Check if user already exists
    const existingUser = await this.touristRepository.findOne({
      where: [{ email }, { phoneNumber }],
    });

    if (existingUser) {
      throw new ConflictException('User with this email or phone number already exists');
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 12);

    // Generate digital ID (in real implementation, this would be blockchain-generated)
    const digitalId = this.generateDigitalId();

    // Create user
    const tourist = this.touristRepository.create({
      ...userData,
      email,
      phoneNumber,
      digitalId,
      // In a real implementation, password would be stored separately
    });

    const savedTourist = await this.touristRepository.save(tourist);

    // Generate tokens
    const tokens = await this.generateTokens(savedTourist.id);

    return {
      tourist: this.sanitizeUser(savedTourist),
      ...tokens,
    };
  }

  async validateUser(email: string, password: string): Promise<any> {
    const user = await this.touristRepository.findOne({ where: { email } });
    
    if (user && await bcrypt.compare(password, user.password)) {
      const { password, ...result } = user;
      return result;
    }
    return null;
  }

  async login(user: any) {
    const tokens = await this.generateTokens(user.id);
    
    // Store refresh token in Redis
    await this.redisService.set(
      `refresh_token:${user.id}`,
      tokens.refreshToken,
      7 * 24 * 60 * 60, // 7 days
    );

    return {
      tourist: this.sanitizeUser(user),
      ...tokens,
    };
  }

  async refreshToken(refreshToken: string) {
    try {
      const payload = this.jwtService.verify(refreshToken);
      const storedToken = await this.redisService.get(`refresh_token:${payload.sub}`);
      
      if (storedToken !== refreshToken) {
        throw new UnauthorizedException('Invalid refresh token');
      }

      const user = await this.touristRepository.findOne({
        where: { id: payload.sub },
      });

      if (!user) {
        throw new UnauthorizedException('User not found');
      }

      const tokens = await this.generateTokens(user.id);
      
      // Update refresh token in Redis
      await this.redisService.set(
        `refresh_token:${user.id}`,
        tokens.refreshToken,
        7 * 24 * 60 * 60,
      );

      return {
        tourist: this.sanitizeUser(user),
        ...tokens,
      };
    } catch (error) {
      throw new UnauthorizedException('Invalid refresh token');
    }
  }

  async getProfile(userId: string) {
    const user = await this.touristRepository.findOne({
      where: { id: userId },
    });

    if (!user) {
      throw new UnauthorizedException('User not found');
    }

    return this.sanitizeUser(user);
  }

  async logout(userId: string) {
    // Remove refresh token from Redis
    await this.redisService.del(`refresh_token:${userId}`);
    
    return { message: 'Logout successful' };
  }

  private async generateTokens(userId: string) {
    const payload = { sub: userId, email: '' };
    
    const [accessToken, refreshToken] = await Promise.all([
      this.jwtService.signAsync(payload, { expiresIn: '15m' }),
      this.jwtService.signAsync(payload, { expiresIn: '7d' }),
    ]);

    return {
      accessToken,
      refreshToken,
    };
  }

  private generateDigitalId(): string {
    // In real implementation, this would be generated by blockchain
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substr(2, 5);
    return `TID_${timestamp}_${random}`.toUpperCase();
  }

  private sanitizeUser(user: Tourist) {
    const { ...sanitized } = user;
    return sanitized;
  }
}
